### ISSUE TITLE
训练的时候（数据量600多），loss降得很快，一下子就0.2左右，两个epoch就基本饱和，测试的时候都是灰色的，想请教大佬，是什么原因

### ISSUE THREAD

**Issue by xll426** [mohuazheliu/ResUnet-a#1]
qq772246003，能方便交流一下吗？感谢

**Comment by ChienWong** [comment]
我的错，这边训练的时候做了归一化，但是预测的时候没有

**Comment by ChienWong** [comment]
这个模型在我这边比不上Unet++，所以没怎么关注

**Comment by xll426** [comment]
请问Unet++,在遥感解译效果相对好，您在gihub上有关这个模型的代码介绍吗



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "ChienWong"<notifications@github.com&gt;; 
发送时间: 2020年4月7日(星期二) 晚上10:38
收件人: "ChienWong/ResUnet-a"<ResUnet-a@noreply.github.com&gt;; 
抄送: "l¤l"<772246003@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [ChienWong/ResUnet-a] 训练的时候（数据量600多），loss降得很快，一下子就0.2左右，两个epoch就基本饱和，测试的时候都是灰色的，想请教大佬，是什么原因 (#1)





 
这个模型在我这边比不上Unet++，所以没怎么关注

**Comment by ChienWong** [comment]
我这边只有代码，并没有写readme

**Comment by ChienWong** [comment]
代码已经改好了，去掉了训练的归一化

**Comment by xll426** [comment]
如果方便，代码能借我参考一下吗（非商业，写论文用）
 



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "ChienWong"<notifications@github.com&gt;; 
发送时间: 2020年4月7日(星期二) 晚上10:48
收件人: "ChienWong/ResUnet-a"<ResUnet-a@noreply.github.com&gt;; 
抄送: "l¤l"<772246003@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [ChienWong/ResUnet-a] 训练的时候（数据量600多），loss降得很快，一下子就0.2左右，两个epoch就基本饱和，测试的时候都是灰色的，想请教大佬，是什么原因 (#1)





 
代码已经改好了，去掉了训练的归一化

**Comment by xll426** [comment]
感谢大佬
 



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "ChienWong"<notifications@github.com&gt;; 
发送时间: 2020年4月7日(星期二) 晚上10:48
收件人: "ChienWong/ResUnet-a"<ResUnet-a@noreply.github.com&gt;; 
抄送: "l¤l"<772246003@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [ChienWong/ResUnet-a] 训练的时候（数据量600多），loss降得很快，一下子就0.2左右，两个epoch就基本饱和，测试的时候都是灰色的，想请教大佬，是什么原因 (#1)





 
代码已经改好了，去掉了训练的归一化

**Comment by ChienWong** [comment]
发你邮箱了

**Comment by xll426** [comment]
感谢大佬
 



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "ChienWong"<notifications@github.com&gt;; 
发送时间: 2020年4月7日(星期二) 晚上10:59
收件人: "ChienWong/ResUnet-a"<ResUnet-a@noreply.github.com&gt;; 
抄送: "l¤l"<772246003@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [ChienWong/ResUnet-a] 训练的时候（数据量600多），loss降得很快，一下子就0.2左右，两个epoch就基本饱和，测试的时候都是灰色的，想请教大佬，是什么原因 (#1)





 
发你邮箱了

**Comment by xll426** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"ChienWong"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月7日(星期二) 晚上10:59
收件人:&nbsp;"ChienWong/ResUnet-a"<ResUnet-a@noreply.github.com&gt;;
抄送:&nbsp;"l¤l"<772246003@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ChienWong/ResUnet-a] 训练的时候（数据量600多），loss降得很快，一下子就0.2左右，两个epoch就基本饱和，测试的时候都是灰色的，想请教大佬，是什么原因 (#1)





 
发你邮箱了
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.


从QQ邮箱发来的超大附件

ResUnet-a-master.rar (839.55M, 2020年05月10日 07:56 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=79333535fd06e3a8c3ba321b1736564c04570000010e5d561d0a5051011b5057565518540307004e065501500357050754025601312264315540605b544249021d5e54464553164d425247350c&code=035516dc

**Comment by misaka100001** [comment]
大哥，我也遇到了同样的问题，请问是怎么解决的啊
